/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'Lots',
      [
        {
          UserId: 1,
          ProductId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 10,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 15,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 17,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 20,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 21,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 22,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 23,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 24,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 25,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 26,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 27,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 28,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 29,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 30,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 31,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 32,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 33,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 34,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 35,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 36,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 37,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 38,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 39,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 40,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 41,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 42,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 43,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 44,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 45,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 46,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 47,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 48,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 49,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 50,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 51,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 52,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 53,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 54,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 55,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 56,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 57,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 58,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 59,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 60,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 61,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 62,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 63,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 64,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 65,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 66,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 67,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 68,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 69,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 70,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 71,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 72,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 73,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 74,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 75,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 76,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 77,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 78,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 79,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 80,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 81,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 82,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 83,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 84,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 85,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 86,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 87,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 88,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 89,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 90,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 91,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 92,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 93,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 94,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 95,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 96,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 97,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 98,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 99,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 100,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 101,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 102,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 103,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 104,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 105,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 106,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 107,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 108,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 109,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 110,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 111,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 112,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 113,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 114,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 115,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 116,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 117,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 118,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 119,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 120,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 121,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 122,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 123,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 124,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 125,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 126,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 127,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 128,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 129,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 130,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 131,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 132,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 133,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 134,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 135,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 136,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 137,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 138,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 139,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 140,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 141,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 142,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 143,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          UserId: 1,
          ProductId: 144,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],

    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('Lots');
  },
};
